/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fenetre_recherche_wg (void);
GtkWidget* create_fenetre_capteurwg (void);
