/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_afficher (void)
{
  GtkWidget *fenetre_afficher;
  GtkWidget *vbox1;
  GtkWidget *vbox2;
  GtkWidget *label26;
  GtkWidget *hbox14;
  GtkWidget *label27;
  GtkWidget *entry1;
  GtkWidget *actualiser;
  GtkWidget *alignment13;
  GtkWidget *hbox19;
  GtkWidget *image12;
  GtkWidget *label37;
  GtkWidget *button_capteurs_alarmats_wg;
  GtkWidget *alignment19;
  GtkWidget *hbox25;
  GtkWidget *image18;
  GtkWidget *label54;
  GtkWidget *buttonrechwg;
  GtkWidget *alignment12;
  GtkWidget *hbox18;
  GtkWidget *image11;
  GtkWidget *label31;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview1;
  GtkWidget *hbox13;
  GtkWidget *button_ajout_wael;
  GtkWidget *alignment9;
  GtkWidget *hbox15;
  GtkWidget *image8;
  GtkWidget *label28;
  GtkWidget *button2mowg;
  GtkWidget *alignment10;
  GtkWidget *hbox16;
  GtkWidget *image9;
  GtkWidget *label29;
  GtkWidget *button_supp_wael;
  GtkWidget *alignment11;
  GtkWidget *hbox17;
  GtkWidget *image10;
  GtkWidget *label30;

  fenetre_afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_afficher, 750, 650);
  gtk_window_set_title (GTK_WINDOW (fenetre_afficher), _("fenetre_afficher"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (fenetre_afficher), vbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, FALSE, TRUE, 0);

  label26 = gtk_label_new (_("Gestion des capteurs"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (vbox2), label26, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label26, -1, 46);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox14, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hbox14, -1, 49);

  label27 = gtk_label_new (_("Id \303\240 supprim\303\251:"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox14), label27, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label27, 120, -1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox14), entry1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry1, 197, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  actualiser = gtk_button_new ();
  gtk_widget_show (actualiser);
  gtk_box_pack_start (GTK_BOX (hbox14), actualiser, TRUE, FALSE, 2);
  gtk_widget_set_size_request (actualiser, 104, -1);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (actualiser), alignment13);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox19);

  image12 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox19), image12, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox19), label37, FALSE, TRUE, 0);

  button_capteurs_alarmats_wg = gtk_button_new ();
  gtk_widget_show (button_capteurs_alarmats_wg);
  gtk_box_pack_start (GTK_BOX (hbox14), button_capteurs_alarmats_wg, TRUE, FALSE, 0);
  gtk_widget_set_size_request (button_capteurs_alarmats_wg, 162, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button_capteurs_alarmats_wg), alignment19);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox25);

  image18 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox25), image18, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("Capteurs alarmants"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox25), label54, FALSE, FALSE, 0);

  buttonrechwg = gtk_button_new ();
  gtk_widget_show (buttonrechwg);
  gtk_box_pack_end (GTK_BOX (hbox14), buttonrechwg, FALSE, FALSE, 13);
  gtk_widget_set_size_request (buttonrechwg, 99, 27);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonrechwg), alignment12);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox18);

  image11 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox18), image11, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox18), label31, FALSE, FALSE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow2, FALSE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview1);
  gtk_widget_set_size_request (treeview1, 300, 348);

  hbox13 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox13);
  gtk_box_pack_end (GTK_BOX (vbox1), hbox13, TRUE, TRUE, 0);

  button_ajout_wael = gtk_button_new ();
  gtk_widget_show (button_ajout_wael);
  gtk_box_pack_start (GTK_BOX (hbox13), button_ajout_wael, FALSE, TRUE, 0);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_ajout_wael), alignment9);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox15);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox15), image8, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox15), label28, FALSE, FALSE, 0);

  button2mowg = gtk_button_new ();
  gtk_widget_show (button2mowg);
  gtk_box_pack_start (GTK_BOX (hbox13), button2mowg, FALSE, TRUE, 0);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button2mowg), alignment10);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox16);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox16), image9, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox16), label29, FALSE, FALSE, 0);

  button_supp_wael = gtk_button_new ();
  gtk_widget_show (button_supp_wael);
  gtk_box_pack_start (GTK_BOX (hbox13), button_supp_wael, FALSE, TRUE, 0);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_supp_wael), alignment11);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox17);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox17), image10, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox17), label30, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_capteurs_alarmats_wg, "clicked",
                    G_CALLBACK (on_button_capteurs_alarmats_wg_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonrechwg, "clicked",
                    G_CALLBACK (on_buttonrechwg_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_ajout_wael, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2mowg, "clicked",
                    G_CALLBACK (on_button2mowg_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supp_wael, "clicked",
                    G_CALLBACK (on_button_supp_wael_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_afficher, fenetre_afficher, "fenetre_afficher");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label26, "label26");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label27, "label27");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, actualiser, "actualiser");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image12, "image12");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label37, "label37");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, button_capteurs_alarmats_wg, "button_capteurs_alarmats_wg");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image18, "image18");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label54, "label54");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, buttonrechwg, "buttonrechwg");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image11, "image11");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label31, "label31");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, button_ajout_wael, "button_ajout_wael");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image8, "image8");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label28, "label28");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, button2mowg, "button2mowg");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image9, "image9");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label29, "label29");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, button_supp_wael, "button_supp_wael");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image10, "image10");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label30, "label30");

  return fenetre_afficher;
}

GtkWidget*
create_fenetre_ajout (void)
{
  GtkWidget *fenetre_ajout;
  GtkWidget *fixed1wg;
  GtkWidget *entry3wg;
  GtkObject *spinbutton1wg_adj;
  GtkWidget *spinbutton1wg;
  GtkObject *spinbutton2wg_adj;
  GtkWidget *spinbutton2wg;
  GtkWidget *entry5wg;
  GtkWidget *hbox7wg;
  GtkWidget *button5wg;
  GtkWidget *alignment8;
  GtkWidget *hbox9;
  GtkWidget *image7;
  GtkWidget *label25;
  GtkWidget *button6wg;
  GtkWidget *alignment15;
  GtkWidget *hbox21;
  GtkWidget *image14;
  GtkWidget *label41;
  GtkWidget *entry2;
  GtkWidget *combobox1;
  GtkWidget *combobox2;
  GtkWidget *combobox3;
  GtkWidget *label35;
  GtkWidget *label34;
  GtkObject *spinbutton3wg_adj;
  GtkWidget *spinbutton3wg;
  GtkWidget *label21wg;
  GtkWidget *label22wg;
  GtkObject *spinbutton4wg_adj;
  GtkWidget *spinbutton4wg;
  GtkWidget *label40;
  GtkWidget *label39;
  GtkWidget *label32;
  GtkWidget *label23wg;
  GtkWidget *label36;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *button5;
  GtkWidget *alignment14;
  GtkWidget *hbox20;
  GtkWidget *image13;
  GtkWidget *label38;
  GtkWidget *buttonmodifwg;
  GtkWidget *alignment16;
  GtkWidget *hbox22;
  GtkWidget *image15;
  GtkWidget *label42;
  GtkWidget *identrywg;
  GtkWidget *label20wg;
  GtkWidget *label19wg;
  GtkWidget *label33;
  GtkWidget *label43wg;

  fenetre_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_ajout, 650, -1);
  gtk_window_set_title (GTK_WINDOW (fenetre_ajout), _("fenetre_ajout"));

  fixed1wg = gtk_fixed_new ();
  gtk_widget_show (fixed1wg);
  gtk_container_add (GTK_CONTAINER (fenetre_ajout), fixed1wg);

  entry3wg = gtk_entry_new ();
  gtk_widget_show (entry3wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), entry3wg, 168, 64);
  gtk_widget_set_size_request (entry3wg, 150, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3wg), 8226);

  spinbutton1wg_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1wg = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1wg_adj), 1, 2);
  gtk_widget_show (spinbutton1wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), spinbutton1wg, 416, 248);
  gtk_widget_set_size_request (spinbutton1wg, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton1wg), TRUE);

  spinbutton2wg_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2wg = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2wg_adj), 1, 2);
  gtk_widget_show (spinbutton2wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), spinbutton2wg, 416, 327);
  gtk_widget_set_size_request (spinbutton2wg, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton2wg), TRUE);

  entry5wg = gtk_entry_new ();
  gtk_widget_show (entry5wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), entry5wg, 168, 114);
  gtk_widget_set_size_request (entry5wg, 150, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5wg), 8226);

  hbox7wg = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox7wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), hbox7wg, 45, 410);
  gtk_widget_set_size_request (hbox7wg, 550, 89);

  button5wg = gtk_button_new ();
  gtk_widget_show (button5wg);
  gtk_box_pack_start (GTK_BOX (hbox7wg), button5wg, TRUE, TRUE, 0);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0.02, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button5wg), alignment8);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox9);

  image7 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox9), image7, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox9), label25, FALSE, FALSE, 0);

  button6wg = gtk_button_new ();
  gtk_widget_show (button6wg);
  gtk_box_pack_start (GTK_BOX (hbox7wg), button6wg, TRUE, TRUE, 0);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button6wg), alignment15);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox21);

  image14 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox21), image14, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox21), label41, FALSE, FALSE, 0);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1wg), entry2, 168, 160);
  gtk_widget_set_size_request (entry2, 150, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed1wg), combobox1, 561, 29);
  gtk_widget_set_size_request (combobox1, 47, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("31"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (combobox1), TRUE);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed1wg), combobox2, 561, 101);
  gtk_widget_set_size_request (combobox2, 47, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("12"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (combobox2), TRUE);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed1wg), combobox3, 561, 174);
  gtk_widget_set_size_request (combobox3, 63, 34);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2015"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2016"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2017"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2018"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2019"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2021"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2022"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2023"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2024"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2025"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2026"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2027"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2028"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2029"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("2030"));

  label35 = gtk_label_new (_("Ann\303\251e de mise en marche :"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label35, 344, 176);
  gtk_widget_set_size_request (label35, 184, 32);

  label34 = gtk_label_new (_("Mois de mise en marche :"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label34, 352, 104);
  gtk_widget_set_size_request (label34, 168, 32);

  spinbutton3wg_adj = gtk_adjustment_new (1, -20, 100, 1, 10, 10);
  spinbutton3wg = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3wg_adj), 1, 2);
  gtk_widget_show (spinbutton3wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), spinbutton3wg, 576, 248);
  gtk_widget_set_size_request (spinbutton3wg, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton3wg), TRUE);

  label21wg = gtk_label_new (_("Seuil max1  :"));
  gtk_widget_show (label21wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label21wg, 320, 240);
  gtk_widget_set_size_request (label21wg, 88, 40);

  label22wg = gtk_label_new (_("Seuil max2 :"));
  gtk_widget_show (label22wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label22wg, 320, 320);
  gtk_widget_set_size_request (label22wg, 88, 40);

  spinbutton4wg_adj = gtk_adjustment_new (1, -20, 100, 1, 10, 10);
  spinbutton4wg = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4wg_adj), 1, 2);
  gtk_widget_show (spinbutton4wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), spinbutton4wg, 576, 328);
  gtk_widget_set_size_request (spinbutton4wg, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton4wg), TRUE);

  label40 = gtk_label_new (_("Seuil min2 : "));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label40, 481, 319);
  gtk_widget_set_size_request (label40, 88, 40);

  label39 = gtk_label_new (_("Seuil min1 :"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label39, 481, 240);
  gtk_widget_set_size_request (label39, 88, 40);

  label32 = gtk_label_new (_("Marque :"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label32, 72, 160);
  gtk_widget_set_size_request (label32, 64, 24);

  label23wg = gtk_label_new (_("Type :"));
  gtk_widget_show (label23wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label23wg, 72, 224);
  gtk_widget_set_size_request (label23wg, 59, 28);

  label36 = gtk_label_new (_("Etat:"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label36, 72, 328);
  gtk_widget_set_size_request (label36, 49, 17);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Humidit\303\251"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed1wg), radiobutton2, 168, 248);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Temp\303\251rature"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed1wg), radiobutton1, 168, 208);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("En marche"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1wg), checkbutton1, 152, 312);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("En panne"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed1wg), checkbutton2, 152, 344);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed1wg), button5, 321, 502);
  gtk_widget_set_size_request (button5, 272, 85);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button5), alignment14);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox20);

  image13 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox20), image13, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox20), label38, FALSE, FALSE, 0);

  buttonmodifwg = gtk_button_new ();
  gtk_widget_show (buttonmodifwg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), buttonmodifwg, 46, 503);
  gtk_widget_set_size_request (buttonmodifwg, 275, 85);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonmodifwg), alignment16);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox22);

  image15 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox22), image15, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox22), label42, FALSE, FALSE, 0);

  identrywg = gtk_entry_new ();
  gtk_widget_show (identrywg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), identrywg, 168, 18);
  gtk_widget_set_size_request (identrywg, 150, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (identrywg), 8226);

  label20wg = gtk_label_new (_("Id :"));
  gtk_widget_show (label20wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label20wg, 72, 113);
  gtk_widget_set_size_request (label20wg, 48, 25);

  label19wg = gtk_label_new (_("Nom du capteur :"));
  gtk_widget_show (label19wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label19wg, 40, 57);
  gtk_widget_set_size_request (label19wg, 120, 40);

  label33 = gtk_label_new (_("Jour de mise en marche :"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label33, 344, 24);
  gtk_widget_set_size_request (label33, 176, 48);

  label43wg = gtk_label_new (_("Id a modifier :"));
  gtk_widget_show (label43wg);
  gtk_fixed_put (GTK_FIXED (fixed1wg), label43wg, 61, 21);
  gtk_widget_set_size_request (label43wg, 97, 17);

  g_signal_connect ((gpointer) button5wg, "clicked",
                    G_CALLBACK (on_button5wg_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6wg, "clicked",
                    G_CALLBACK (on_button6wg_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifwg, "clicked",
                    G_CALLBACK (on_buttonmodifwg_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_ajout, fenetre_ajout, "fenetre_ajout");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, fixed1wg, "fixed1wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, entry3wg, "entry3wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, spinbutton1wg, "spinbutton1wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, spinbutton2wg, "spinbutton2wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, entry5wg, "entry5wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox7wg, "hbox7wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, button5wg, "button5wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image7, "image7");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label25, "label25");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, button6wg, "button6wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image14, "image14");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label41, "label41");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label35, "label35");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label34, "label34");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, spinbutton3wg, "spinbutton3wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label21wg, "label21wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label22wg, "label22wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, spinbutton4wg, "spinbutton4wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label40, "label40");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label39, "label39");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label32, "label32");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label23wg, "label23wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label36, "label36");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, button5, "button5");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image13, "image13");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label38, "label38");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, buttonmodifwg, "buttonmodifwg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image15, "image15");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label42, "label42");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, identrywg, "identrywg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label20wg, "label20wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label19wg, "label19wg");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label33, "label33");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label43wg, "label43wg");

  return fenetre_ajout;
}

GtkWidget*
create_fenetre_recherche_wg (void)
{
  GtkWidget *fenetre_recherche_wg;
  GtkWidget *fixed3;
  GtkWidget *treeview2;
  GtkWidget *entryrechwg;
  GtkWidget *label44wg;
  GtkWidget *buttonrecherchwg;
  GtkWidget *alignment17;
  GtkWidget *hbox23;
  GtkWidget *image16;
  GtkWidget *label43;
  GtkWidget *buttonretourrechwg;
  GtkWidget *alignment18;
  GtkWidget *hbox24;
  GtkWidget *image17;
  GtkWidget *label44;

  fenetre_recherche_wg = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_recherche_wg, 750, 650);
  gtk_window_set_title (GTK_WINDOW (fenetre_recherche_wg), _("fenetre_recherche_wg"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (fenetre_recherche_wg), fixed3);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview2, 40, 112);
  gtk_widget_set_size_request (treeview2, 672, 448);

  entryrechwg = gtk_entry_new ();
  gtk_widget_show (entryrechwg);
  gtk_fixed_put (GTK_FIXED (fixed3), entryrechwg, 264, 48);
  gtk_widget_set_size_request (entryrechwg, 181, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryrechwg), 8226);

  label44wg = gtk_label_new (_("Id \303\240 rechercher :"));
  gtk_widget_show (label44wg);
  gtk_fixed_put (GTK_FIXED (fixed3), label44wg, 120, 48);
  gtk_widget_set_size_request (label44wg, 120, 28);

  buttonrecherchwg = gtk_button_new ();
  gtk_widget_show (buttonrecherchwg);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonrecherchwg, 488, 48);
  gtk_widget_set_size_request (buttonrecherchwg, 129, 44);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonrecherchwg), alignment17);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox23);

  image16 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox23), image16, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox23), label43, FALSE, FALSE, 0);

  buttonretourrechwg = gtk_button_new ();
  gtk_widget_show (buttonretourrechwg);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonretourrechwg, 328, 584);
  gtk_widget_set_size_request (buttonretourrechwg, 109, 43);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonretourrechwg), alignment18);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox24);

  image17 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox24), image17, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox24), label44, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonrecherchwg, "clicked",
                    G_CALLBACK (on_buttonrecherchwg_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourrechwg, "clicked",
                    G_CALLBACK (on_buttonretourrechwg_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_recherche_wg, fenetre_recherche_wg, "fenetre_recherche_wg");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, entryrechwg, "entryrechwg");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, label44wg, "label44wg");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, buttonrecherchwg, "buttonrecherchwg");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, image16, "image16");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, label43, "label43");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, buttonretourrechwg, "buttonretourrechwg");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, image17, "image17");
  GLADE_HOOKUP_OBJECT (fenetre_recherche_wg, label44, "label44");

  return fenetre_recherche_wg;
}

GtkWidget*
create_fenetre_capteurwg (void)
{
  GtkWidget *fenetre_capteurwg;
  GtkWidget *fixed4;
  GtkObject *spinbuttonmin1wg_adj;
  GtkWidget *spinbuttonmin1wg;
  GtkObject *spinbuttonmin2wg_adj;
  GtkWidget *spinbuttonmin2wg;
  GtkObject *spinbuttonmax1wg_adj;
  GtkWidget *spinbuttonmax1wg;
  GtkObject *spinbuttonmax2wg_adj;
  GtkWidget *spinbuttonmax2wg;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkObject *spinbuttonhummin1wg_adj;
  GtkWidget *spinbuttonhummin1wg;
  GtkObject *spinbuttonhummin2wg_adj;
  GtkWidget *spinbuttonhummin2wg;
  GtkObject *spinbuttonhummax1wg_adj;
  GtkWidget *spinbuttonhummax1wg;
  GtkObject *spinbuttonhummax2wg_adj;
  GtkWidget *spinbuttonhummax2wg;
  GtkWidget *capteurtemps;
  GtkWidget *capteurhumdwg;
  GtkWidget *label45wg;
  GtkWidget *label53;
  GtkWidget *label52;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *label49wg;
  GtkWidget *button_retour_capteur_wg;
  GtkWidget *alignment20;
  GtkWidget *hbox26;
  GtkWidget *image19;
  GtkWidget *label55;

  fenetre_capteurwg = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_capteurwg, 650, -1);
  gtk_window_set_title (GTK_WINDOW (fenetre_capteurwg), _("window1"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (fenetre_capteurwg), fixed4);

  spinbuttonmin1wg_adj = gtk_adjustment_new (1, -100, 1000, 1, 10, 10);
  spinbuttonmin1wg = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmin1wg_adj), 1, 0);
  gtk_widget_show (spinbuttonmin1wg);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonmin1wg, 72, 80);
  gtk_widget_set_size_request (spinbuttonmin1wg, 60, 27);

  spinbuttonmin2wg_adj = gtk_adjustment_new (1, -100, 1000, 1, 10, 10);
  spinbuttonmin2wg = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmin2wg_adj), 1, 0);
  gtk_widget_show (spinbuttonmin2wg);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonmin2wg, 152, 80);
  gtk_widget_set_size_request (spinbuttonmin2wg, 60, 27);

  spinbuttonmax1wg_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 10);
  spinbuttonmax1wg = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmax1wg_adj), 1, 0);
  gtk_widget_show (spinbuttonmax1wg);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonmax1wg, 272, 80);
  gtk_widget_set_size_request (spinbuttonmax1wg, 60, 27);

  spinbuttonmax2wg_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 10);
  spinbuttonmax2wg = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmax2wg_adj), 1, 0);
  gtk_widget_show (spinbuttonmax2wg);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonmax2wg, 376, 80);
  gtk_widget_set_size_request (spinbuttonmax2wg, 60, 27);

  label45 = gtk_label_new (_("Min1"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed4), label45, 69, 48);
  gtk_widget_set_size_request (label45, 49, 17);

  label46 = gtk_label_new (_("Min2"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed4), label46, 158, 48);
  gtk_widget_set_size_request (label46, 49, 17);

  label47 = gtk_label_new (_("Max1"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed4), label47, 279, 48);
  gtk_widget_set_size_request (label47, 49, 17);

  label48 = gtk_label_new (_("Max2"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed4), label48, 381, 48);
  gtk_widget_set_size_request (label48, 49, 17);

  spinbuttonhummin1wg_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonhummin1wg = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonhummin1wg_adj), 1, 0);
  gtk_widget_show (spinbuttonhummin1wg);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonhummin1wg, 80, 288);
  gtk_widget_set_size_request (spinbuttonhummin1wg, 60, 27);

  spinbuttonhummin2wg_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonhummin2wg = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonhummin2wg_adj), 1, 0);
  gtk_widget_show (spinbuttonhummin2wg);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonhummin2wg, 176, 288);
  gtk_widget_set_size_request (spinbuttonhummin2wg, 60, 27);

  spinbuttonhummax1wg_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonhummax1wg = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonhummax1wg_adj), 1, 0);
  gtk_widget_show (spinbuttonhummax1wg);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonhummax1wg, 320, 288);
  gtk_widget_set_size_request (spinbuttonhummax1wg, 60, 27);

  spinbuttonhummax2wg_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonhummax2wg = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonhummax2wg_adj), 1, 0);
  gtk_widget_show (spinbuttonhummax2wg);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonhummax2wg, 448, 288);
  gtk_widget_set_size_request (spinbuttonhummax2wg, 60, 27);

  capteurtemps = gtk_button_new_with_mnemonic (_("Capteurs temperature alarmants"));
  gtk_widget_show (capteurtemps);
  gtk_fixed_put (GTK_FIXED (fixed4), capteurtemps, 144, 152);
  gtk_widget_set_size_request (capteurtemps, 244, 35);

  capteurhumdwg = gtk_button_new_with_mnemonic (_("Capteurs humidit\303\251 alarmants"));
  gtk_widget_show (capteurhumdwg);
  gtk_fixed_put (GTK_FIXED (fixed4), capteurhumdwg, 144, 384);
  gtk_widget_set_size_request (capteurhumdwg, 236, 35);

  label45wg = gtk_label_new (_("label45"));
  gtk_widget_show (label45wg);
  gtk_fixed_put (GTK_FIXED (fixed4), label45wg, 48, 216);
  gtk_widget_set_size_request (label45wg, 400, 32);

  label53 = gtk_label_new (_("Max2"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed4), label53, 456, 267);
  gtk_widget_set_size_request (label53, 50, 16);

  label52 = gtk_label_new (_("Max1"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed4), label52, 328, 267);
  gtk_widget_set_size_request (label52, 48, 17);

  label50 = gtk_label_new (_("Min1"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed4), label50, 86, 266);
  gtk_widget_set_size_request (label50, 49, 17);

  label51 = gtk_label_new (_("Min2"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed4), label51, 183, 267);
  gtk_widget_set_size_request (label51, 49, 17);

  label49wg = gtk_label_new (_("label49wg"));
  gtk_widget_show (label49wg);
  gtk_fixed_put (GTK_FIXED (fixed4), label49wg, 64, 504);
  gtk_widget_set_size_request (label49wg, 400, 32);

  button_retour_capteur_wg = gtk_button_new ();
  gtk_widget_show (button_retour_capteur_wg);
  gtk_fixed_put (GTK_FIXED (fixed4), button_retour_capteur_wg, 248, 592);
  gtk_widget_set_size_request (button_retour_capteur_wg, 105, 43);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button_retour_capteur_wg), alignment20);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox26);

  image19 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox26), image19, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox26), label55, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) capteurtemps, "clicked",
                    G_CALLBACK (on_capteurtemps_clicked),
                    NULL);
  g_signal_connect ((gpointer) capteurhumdwg, "clicked",
                    G_CALLBACK (on_capteurhumdwg_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_capteur_wg, "clicked",
                    G_CALLBACK (on_button_retour_capteur_wg_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_capteurwg, fenetre_capteurwg, "fenetre_capteurwg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, spinbuttonmin1wg, "spinbuttonmin1wg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, spinbuttonmin2wg, "spinbuttonmin2wg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, spinbuttonmax1wg, "spinbuttonmax1wg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, spinbuttonmax2wg, "spinbuttonmax2wg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, label45, "label45");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, label46, "label46");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, label47, "label47");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, label48, "label48");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, spinbuttonhummin1wg, "spinbuttonhummin1wg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, spinbuttonhummin2wg, "spinbuttonhummin2wg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, spinbuttonhummax1wg, "spinbuttonhummax1wg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, spinbuttonhummax2wg, "spinbuttonhummax2wg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, capteurtemps, "capteurtemps");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, capteurhumdwg, "capteurhumdwg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, label45wg, "label45wg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, label53, "label53");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, label52, "label52");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, label50, "label50");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, label51, "label51");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, label49wg, "label49wg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, button_retour_capteur_wg, "button_retour_capteur_wg");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, image19, "image19");
  GLADE_HOOKUP_OBJECT (fenetre_capteurwg, label55, "label55");

  return fenetre_capteurwg;
}

